apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: vm82yow6z-python-gitops
  description: This is GitOps manifest for vm82yow6z-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: vm82yow6z-python
    backstage.io/kubernetes-id: vm82yow6z-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: vm82yow6z-python   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:vm82yow6z-python
