apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: vm82yow6z-python
  janus-idp.io/tekton: vm82yow6z-python
  backstage.io/kubernetes-id: vm82yow6z-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: vm82yow6z-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
