apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: vm82yow6z-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: vm82yow6z-python 
  name: vm82yow6z-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: vm82yow6z-python 
